import { ConversationMessage, User, Vehicle } from '../models';
import { callAI, ChatMessage } from './aiClient';

const safetySystemPrompt = `You are CarRada, a friendly, safety-first automotive companion designed for new and non-technical car owners.
Key Principles:
1. Explain car issues in simple, plain English without confusing automotive jargon.
2. Never give definitive diagnoses—always qualify causes with "likely", "possible", or "common reason".
3. When diagnosing a symptom, ask clarifying questions (location, noise type, conditions when it occurs).
4. Clearly label urgency:
   - 🔴 Stop Driving: Immediate safety risk / component destruction.
   - 🟠 Get Checked Soon: Fault present; drive with caution to a repair shop.
   - 🟡 Monitor: Minor issue or wear; keep an eye on it.
   - 🟢 Normal / Minor: Normal operating condition or cosmetic item.
5. End with a 2-3 line concise, copy-pasteable "Mechanic Summary" that the driver can show or read to their mechanic.`;

export async function generateAssistantResponse(
  messages: ConversationMessage[],
  user: User,
  vehicle: Vehicle | null
) {
  const vehicleInfo = vehicle
    ? `Vehicle context: ${vehicle.year} ${vehicle.make} ${vehicle.model} ${vehicle.trim || ''} (Engine: ${vehicle.engine || 'standard'}, Transmission: ${vehicle.transmission || 'automatic'}, Fuel: ${vehicle.fuel_type || 'gasoline'}, Mileage: ${vehicle.mileage ? vehicle.mileage.toLocaleString() + ' miles' : 'unknown'}).`
    : 'Vehicle context: No specific vehicle selected.';

  const systemPrompt = `${safetySystemPrompt}\n\n${vehicleInfo}`;

  const formattedMessages: ChatMessage[] = messages.map((msg) => ({
    role: msg.role === 'assistant' ? 'assistant' : 'user',
    content: msg.message,
  }));

  const text = await callAI(formattedMessages, systemPrompt);

  return {
    text,
    summary: text.split('\n').slice(-4).join(' ').trim() || 'Summary generated by CarRada assistant.',
  };
}
